url: https://hsschulz.github.io
baseurl: /site/

# Site settings
title: Heitor Schulz, Developer
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Heitor Schulz
  pic: 1
  position: Full Stack Developer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/heitor-schulz-79580019a/
    - title: facebook
      url: https://www.facebook.com/heitor.schulz
    - title: 
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/
  - title: bitbucket 
    url: http://bitbucket.org/
  - title: github
    url: http://github.com/

# Postal address (add as many lines as necessary)
address:
  - line: Vitória, ES
  - line: Brazil

# Build settings
markdown: kramdown
permalink: pretty
